/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/edgecontainer/v1/resources.proto

package com.google.cloud.edgecontainer.v1;

public final class ResourcesProto {
  private ResourcesProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Cluster_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Cluster_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Cluster_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Cluster_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_ClusterNetworking_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_ClusterNetworking_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Fleet_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Fleet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_ClusterUser_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_ClusterUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Authorization_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Authorization_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_NodePool_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_NodePool_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_NodePool_LocalDiskEncryption_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_NodePool_LocalDiskEncryption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_NodePool_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_NodePool_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Machine_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Machine_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Machine_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Machine_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_VpcProject_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_VpcProject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudRouter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudRouter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudVpn_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudVpn_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_VpnConnection_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_LocationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_LocationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_LocationMetadata_AvailableZonesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_LocationMetadata_AvailableZonesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_ZoneMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_ZoneMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_Quota_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_Quota_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_MaintenancePolicy_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_MaintenancePolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_MaintenanceWindow_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_MaintenanceWindow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_RecurringTimeWindow_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_RecurringTimeWindow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_edgecontainer_v1_TimeWindow_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_edgecontainer_v1_TimeWindow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n-google/cloud/edgecontainer/v1/resource"
          + "s.proto\022\035google.cloud.edgecontainer.v1\032\037"
          + "google/api/field_behavior.proto\032\031google/"
          + "api/resource.proto\032\037google/protobuf/time"
          + "stamp.proto\032\027google/rpc/status.proto\"\323\006\n"
          + "\007Cluster\022:\n\004name\030\001 \001(\tB,\340A\002\372A&\n$edgecont"
          + "ainer.googleapis.com/Cluster\0224\n\013create_t"
          + "ime\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340"
          + "A\003\0224\n\013update_time\030\003 \001(\0132\032.google.protobu"
          + "f.TimestampB\003\340A\003\022B\n\006labels\030\004 \003(\01322.googl"
          + "e.cloud.edgecontainer.v1.Cluster.LabelsE"
          + "ntry\0228\n\005fleet\030\013 \001(\0132$.google.cloud.edgec"
          + "ontainer.v1.FleetB\003\340A\001\022I\n\nnetworking\030\007 \001"
          + "(\01320.google.cloud.edgecontainer.v1.Clust"
          + "erNetworkingB\003\340A\002\022K\n\rauthorization\030\t \001(\013"
          + "2,.google.cloud.edgecontainer.v1.Authori"
          + "zationB\006\340A\002\340A\005\022&\n\031default_max_pods_per_n"
          + "ode\030\010 \001(\005B\003\340A\001\022\025\n\010endpoint\030\006 \001(\tB\003\340A\003\022#\n"
          + "\026cluster_ca_certificate\030\n \001(\tB\003\340A\003\022Q\n\022ma"
          + "intenance_policy\030\014 \001(\01320.google.cloud.ed"
          + "gecontainer.v1.MaintenancePolicyB\003\340A\001\022\"\n"
          + "\025control_plane_version\030\r \001(\tB\003\340A\003\022\031\n\014nod"
          + "e_version\030\016 \001(\tB\003\340A\003\032-\n\013LabelsEntry\022\013\n\003k"
          + "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:e\352Ab\n$edgeco"
          + "ntainer.googleapis.com/Cluster\022:projects"
          + "/{project}/locations/{location}/clusters"
          + "/{cluster}\"b\n\021ClusterNetworking\022%\n\030clust"
          + "er_ipv4_cidr_blocks\030\001 \003(\tB\003\340A\002\022&\n\031servic"
          + "es_ipv4_cidr_blocks\030\002 \003(\tB\003\340A\002\"6\n\005Fleet\022"
          + "\024\n\007project\030\001 \001(\tB\003\340A\002\022\027\n\nmembership\030\002 \001("
          + "\tB\003\340A\003\"$\n\013ClusterUser\022\025\n\010username\030\001 \001(\tB"
          + "\003\340A\002\"U\n\rAuthorization\022D\n\013admin_users\030\001 \001"
          + "(\0132*.google.cloud.edgecontainer.v1.Clust"
          + "erUserB\003\340A\002\"\204\007\n\010NodePool\022;\n\004name\030\001 \001(\tB-"
          + "\340A\002\372A\'\n%edgecontainer.googleapis.com/Nod"
          + "ePool\0224\n\013create_time\030\002 \001(\0132\032.google.prot"
          + "obuf.TimestampB\003\340A\003\0224\n\013update_time\030\003 \001(\013"
          + "2\032.google.protobuf.TimestampB\003\340A\003\022C\n\006lab"
          + "els\030\004 \003(\01323.google.cloud.edgecontainer.v"
          + "1.NodePool.LabelsEntry\022\025\n\rnode_location\030"
          + "\010 \001(\t\022\027\n\nnode_count\030\006 \001(\005B\003\340A\002\022\026\n\016machin"
          + "e_filter\030\007 \001(\t\022_\n\025local_disk_encryption\030"
          + "\t \001(\0132;.google.cloud.edgecontainer.v1.No"
          + "dePool.LocalDiskEncryptionB\003\340A\001\022\031\n\014node_"
          + "version\030\n \001(\tB\003\340A\003\032\230\002\n\023LocalDiskEncrypti"
          + "on\022:\n\007kms_key\030\001 \001(\tB)\340A\005\372A#\n!cloudkms.go"
          + "ogleapis.com/CryptoKey\022P\n\026kms_key_active"
          + "_version\030\002 \001(\tB0\340A\003\372A*\n(cloudkms.googlea"
          + "pis.com/CryptoKeyVersion\022F\n\rkms_key_stat"
          + "e\030\003 \001(\0162*.google.cloud.edgecontainer.v1."
          + "KmsKeyStateB\003\340A\003\022+\n\nkms_status\030\004 \001(\0132\022.g"
          + "oogle.rpc.StatusB\003\340A\003\032-\n\013LabelsEntry\022\013\n\003"
          + "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:|\352Ay\n%edgec"
          + "ontainer.googleapis.com/NodePool\022Pprojec"
          + "ts/{project}/locations/{location}/cluste"
          + "rs/{cluster}/nodePools/{node_pool}\"\304\003\n\007M"
          + "achine\022:\n\004name\030\001 \001(\tB,\340A\002\372A&\n$edgecontai"
          + "ner.googleapis.com/Machine\0224\n\013create_tim"
          + "e\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003"
          + "\0224\n\013update_time\030\003 \001(\0132\032.google.protobuf."
          + "TimestampB\003\340A\003\022B\n\006labels\030\004 \003(\01322.google."
          + "cloud.edgecontainer.v1.Machine.LabelsEnt"
          + "ry\022\023\n\013hosted_node\030\005 \001(\t\022\014\n\004zone\030\006 \001(\t\022\024\n"
          + "\007version\030\007 \001(\tB\003\340A\003\032-\n\013LabelsEntry\022\013\n\003ke"
          + "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001:e\352Ab\n$edgecon"
          + "tainer.googleapis.com/Machine\022:projects/"
          + "{project}/locations/{location}/machines/"
          + "{machine}\"\330\n\n\rVpnConnection\022@\n\004name\030\001 \001("
          + "\tB2\340A\002\372A,\n*edgecontainer.googleapis.com/"
          + "VpnConnection\0224\n\013create_time\030\002 \001(\0132\032.goo"
          + "gle.protobuf.TimestampB\003\340A\003\0224\n\013update_ti"
          + "me\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A"
          + "\003\022H\n\006labels\030\004 \003(\01328.google.cloud.edgecon"
          + "tainer.v1.VpnConnection.LabelsEntry\022\026\n\016n"
          + "at_gateway_ip\030\005 \001(\t\022Y\n\020bgp_routing_mode\030"
          + "\006 \001(\0162;.google.cloud.edgecontainer.v1.Vp"
          + "nConnection.BgpRoutingModeB\002\030\001\022:\n\007cluste"
          + "r\030\007 \001(\tB)\372A&\n$edgecontainer.googleapis.c"
          + "om/Cluster\022\013\n\003vpc\030\010 \001(\t\022L\n\013vpc_project\030\013"
          + " \001(\01327.google.cloud.edgecontainer.v1.Vpn"
          + "Connection.VpcProject\022 \n\030enable_high_ava"
          + "ilability\030\t \001(\010\022J\n\007details\030\n \001(\01324.googl"
          + "e.cloud.edgecontainer.v1.VpnConnection.D"
          + "etailsB\003\340A\003\0329\n\nVpcProject\022\022\n\nproject_id\030"
          + "\001 \001(\t\022\027\n\017service_account\030\002 \001(\t\032\244\003\n\007Detai"
          + "ls\022I\n\005state\030\001 \001(\0162:.google.cloud.edgecon"
          + "tainer.v1.VpnConnection.Details.State\022\r\n"
          + "\005error\030\002 \001(\t\022V\n\014cloud_router\030\003 \001(\0132@.goo"
          + "gle.cloud.edgecontainer.v1.VpnConnection"
          + ".Details.CloudRouter\022Q\n\ncloud_vpns\030\004 \003(\013"
          + "2=.google.cloud.edgecontainer.v1.VpnConn"
          + "ection.Details.CloudVpn\032\033\n\013CloudRouter\022\014"
          + "\n\004name\030\001 \001(\t\032\033\n\010CloudVpn\022\017\n\007gateway\030\001 \001("
          + "\t\"Z\n\005State\022\025\n\021STATE_UNSPECIFIED\020\000\022\023\n\017STA"
          + "TE_CONNECTED\020\001\022\024\n\020STATE_CONNECTING\020\002\022\017\n\013"
          + "STATE_ERROR\020\003\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001("
          + "\t\022\r\n\005value\030\002 \001(\t:\0028\001\"L\n\016BgpRoutingMode\022 "
          + "\n\034BGP_ROUTING_MODE_UNSPECIFIED\020\000\022\014\n\010REGI"
          + "ONAL\020\001\022\n\n\006GLOBAL\020\002:x\352Au\n*edgecontainer.g"
          + "oogleapis.com/VpnConnection\022Gprojects/{p"
          + "roject}/locations/{location}/vpnConnecti"
          + "ons/{vpn_connection}\"\324\001\n\020LocationMetadat"
          + "a\022\\\n\017available_zones\030\001 \003(\0132C.google.clou"
          + "d.edgecontainer.v1.LocationMetadata.Avai"
          + "lableZonesEntry\032b\n\023AvailableZonesEntry\022\013"
          + "\n\003key\030\001 \001(\t\022:\n\005value\030\002 \001(\0132+.google.clou"
          + "d.edgecontainer.v1.ZoneMetadata:\0028\001\"C\n\014Z"
          + "oneMetadata\0223\n\005quota\030\001 \003(\0132$.google.clou"
          + "d.edgecontainer.v1.Quota\"5\n\005Quota\022\016\n\006met"
          + "ric\030\001 \001(\t\022\r\n\005limit\030\002 \001(\001\022\r\n\005usage\030\003 \001(\001\""
          + "U\n\021MaintenancePolicy\022@\n\006window\030\001 \001(\01320.g"
          + "oogle.cloud.edgecontainer.v1.Maintenance"
          + "Window\"a\n\021MaintenanceWindow\022L\n\020recurring"
          + "_window\030\001 \001(\01322.google.cloud.edgecontain"
          + "er.v1.RecurringTimeWindow\"d\n\023RecurringTi"
          + "meWindow\0229\n\006window\030\001 \001(\0132).google.cloud."
          + "edgecontainer.v1.TimeWindow\022\022\n\nrecurrenc"
          + "e\030\002 \001(\t\"j\n\nTimeWindow\022.\n\nstart_time\030\001 \001("
          + "\0132\032.google.protobuf.Timestamp\022,\n\010end_tim"
          + "e\030\002 \001(\0132\032.google.protobuf.Timestamp*p\n\013K"
          + "msKeyState\022\035\n\031KMS_KEY_STATE_UNSPECIFIED\020"
          + "\000\022\037\n\033KMS_KEY_STATE_KEY_AVAILABLE\020\001\022!\n\035KM"
          + "S_KEY_STATE_KEY_UNAVAILABLE\020\002B\246\003\n!com.go"
          + "ogle.cloud.edgecontainer.v1B\016ResourcesPr"
          + "otoP\001ZJgoogle.golang.org/genproto/google"
          + "apis/cloud/edgecontainer/v1;edgecontaine"
          + "r\352Ax\n!cloudkms.googleapis.com/CryptoKey\022"
          + "Sprojects/{project}/locations/{location}"
          + "/keyRings/{key_ring}/cryptoKeys/{crypto_"
          + "key}\352A\246\001\n(cloudkms.googleapis.com/Crypto"
          + "KeyVersion\022zprojects/{project}/locations"
          + "/{location}/keyRings/{key_ring}/cryptoKe"
          + "ys/{crypto_key}/cryptoKeyVersions/{crypt"
          + "o_key_version}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
            });
    internal_static_google_cloud_edgecontainer_v1_Cluster_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_edgecontainer_v1_Cluster_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Cluster_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "Fleet",
              "Networking",
              "Authorization",
              "DefaultMaxPodsPerNode",
              "Endpoint",
              "ClusterCaCertificate",
              "MaintenancePolicy",
              "ControlPlaneVersion",
              "NodeVersion",
            });
    internal_static_google_cloud_edgecontainer_v1_Cluster_LabelsEntry_descriptor =
        internal_static_google_cloud_edgecontainer_v1_Cluster_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_edgecontainer_v1_Cluster_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Cluster_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_edgecontainer_v1_ClusterNetworking_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_edgecontainer_v1_ClusterNetworking_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_ClusterNetworking_descriptor,
            new java.lang.String[] {
              "ClusterIpv4CidrBlocks", "ServicesIpv4CidrBlocks",
            });
    internal_static_google_cloud_edgecontainer_v1_Fleet_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_edgecontainer_v1_Fleet_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Fleet_descriptor,
            new java.lang.String[] {
              "Project", "Membership",
            });
    internal_static_google_cloud_edgecontainer_v1_ClusterUser_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_edgecontainer_v1_ClusterUser_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_ClusterUser_descriptor,
            new java.lang.String[] {
              "Username",
            });
    internal_static_google_cloud_edgecontainer_v1_Authorization_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_edgecontainer_v1_Authorization_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Authorization_descriptor,
            new java.lang.String[] {
              "AdminUsers",
            });
    internal_static_google_cloud_edgecontainer_v1_NodePool_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_edgecontainer_v1_NodePool_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_NodePool_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "NodeLocation",
              "NodeCount",
              "MachineFilter",
              "LocalDiskEncryption",
              "NodeVersion",
            });
    internal_static_google_cloud_edgecontainer_v1_NodePool_LocalDiskEncryption_descriptor =
        internal_static_google_cloud_edgecontainer_v1_NodePool_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_edgecontainer_v1_NodePool_LocalDiskEncryption_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_NodePool_LocalDiskEncryption_descriptor,
            new java.lang.String[] {
              "KmsKey", "KmsKeyActiveVersion", "KmsKeyState", "KmsStatus",
            });
    internal_static_google_cloud_edgecontainer_v1_NodePool_LabelsEntry_descriptor =
        internal_static_google_cloud_edgecontainer_v1_NodePool_descriptor.getNestedTypes().get(1);
    internal_static_google_cloud_edgecontainer_v1_NodePool_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_NodePool_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_edgecontainer_v1_Machine_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_edgecontainer_v1_Machine_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Machine_descriptor,
            new java.lang.String[] {
              "Name", "CreateTime", "UpdateTime", "Labels", "HostedNode", "Zone", "Version",
            });
    internal_static_google_cloud_edgecontainer_v1_Machine_LabelsEntry_descriptor =
        internal_static_google_cloud_edgecontainer_v1_Machine_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_edgecontainer_v1_Machine_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Machine_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "NatGatewayIp",
              "BgpRoutingMode",
              "Cluster",
              "Vpc",
              "VpcProject",
              "EnableHighAvailability",
              "Details",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_VpcProject_descriptor =
        internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_VpcProject_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_VpcProject_descriptor,
            new java.lang.String[] {
              "ProjectId", "ServiceAccount",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_descriptor =
        internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_descriptor,
            new java.lang.String[] {
              "State", "Error", "CloudRouter", "CloudVpns",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudRouter_descriptor =
        internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudRouter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudRouter_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudVpn_descriptor =
        internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudVpn_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_Details_CloudVpn_descriptor,
            new java.lang.String[] {
              "Gateway",
            });
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_LabelsEntry_descriptor =
        internal_static_google_cloud_edgecontainer_v1_VpnConnection_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_cloud_edgecontainer_v1_VpnConnection_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_VpnConnection_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_edgecontainer_v1_LocationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_edgecontainer_v1_LocationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_LocationMetadata_descriptor,
            new java.lang.String[] {
              "AvailableZones",
            });
    internal_static_google_cloud_edgecontainer_v1_LocationMetadata_AvailableZonesEntry_descriptor =
        internal_static_google_cloud_edgecontainer_v1_LocationMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_edgecontainer_v1_LocationMetadata_AvailableZonesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_LocationMetadata_AvailableZonesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_edgecontainer_v1_ZoneMetadata_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_edgecontainer_v1_ZoneMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_ZoneMetadata_descriptor,
            new java.lang.String[] {
              "Quota",
            });
    internal_static_google_cloud_edgecontainer_v1_Quota_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_edgecontainer_v1_Quota_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_Quota_descriptor,
            new java.lang.String[] {
              "Metric", "Limit", "Usage",
            });
    internal_static_google_cloud_edgecontainer_v1_MaintenancePolicy_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_edgecontainer_v1_MaintenancePolicy_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_MaintenancePolicy_descriptor,
            new java.lang.String[] {
              "Window",
            });
    internal_static_google_cloud_edgecontainer_v1_MaintenanceWindow_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_edgecontainer_v1_MaintenanceWindow_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_MaintenanceWindow_descriptor,
            new java.lang.String[] {
              "RecurringWindow",
            });
    internal_static_google_cloud_edgecontainer_v1_RecurringTimeWindow_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_edgecontainer_v1_RecurringTimeWindow_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_RecurringTimeWindow_descriptor,
            new java.lang.String[] {
              "Window", "Recurrence",
            });
    internal_static_google_cloud_edgecontainer_v1_TimeWindow_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_edgecontainer_v1_TimeWindow_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_edgecontainer_v1_TimeWindow_descriptor,
            new java.lang.String[] {
              "StartTime", "EndTime",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
